# Site settings
title: RBMV
email: robert@robertmitchellv.com
description: "I really enjoy brainstorming + would love to talk with you about any projects that you see my skill set augmenting.  Feel free to use the email to the left or keep my in mind by following me on Twitter or GitHub!  Thanks for stopping by!"
baseurl: "https://robertmitchellv.github.io/"
url: "https://robertmitchellv.github.io/"
twitter_username: robertmitchellv
github_username:  robertmitchellv
linkedin_username: robertmitchellv

timezone: America/Los_Angeles

exclude: ['README.md']

# Build settings
markdown: kramdown
permalink: pretty
